POST {{HostAddress}}translate
Content-Type: application/json
Accept: application/json

[ 
    "urn:epc:id:sgln:0614141.12345.32a%2fb",
    "https://id.gs1.org/414/0614141123450",
    "https://id.gs1.org/8004/952114132a%23b"
]
